version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_HOST=mysql
      - DB_DATABASE=samfon_db
      - DB_USERNAME=samfon_app
      - DB_PASSWORD=Complex-P@ssw0rd-2024!
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: samfon_db
      MYSQL_USER: samfon_app
      MYSQL_PASSWORD: Complex-P@ssw0rd-2024!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data:
